### ISSUE TITLE
multiple excel table calls to same excel file chunks the tables together 

### ISSUE THREAD

**Issue by mbibee** [hackerain/sphinxcontrib-excel-table#1]
I have a spreadsheet with many rows and I would like to document portions of the spreadsheet.
I would like to include a few rows of the spreadsheet, explain a few things about those rows
and then include another set of rows and explain those ... and so on.

If my rst file has: 

```
.. excel-table::
   :file: ../assets/specs/file.xlsx
   :sheet: Transmitter
   :selection: A82:G89

Some text test explaining A82:G89

.. excel-table::
   :file: ../assets/specs/file.xlsx
   :sheet: Transmitter
   :selection: A97:G99

Some text explaining A97:G99

```
the rendered file will chunk both excel table directives so that I get

~~~~~~~

| A97:G99 |
|---------|
| A82:G89 |

Some text test explaining A82:G89
Some text explaining A97:G99

~~~~~~~~

So the tables are getting grouped vertically and the text comes out together.  I would like the 
tables to be distinct and have the text explaining each table

If I instead copy file.xlsx into to different copies file1.xlsx and file2.xlsx (both identical) and then I change my rst file to

```
.. excel-table::
   :file: ../assets/specs/file1.xlsx
   :sheet: Transmitter
   :selection: A82:G89

Some text here: 

.. excel-table::
   :file: ../assets/specs/file2.xlsx
   :sheet: Transmitter
   :selection: A97:G99

```
Then the tables render separately from each other.  Is there a way to reference the same .xlsx multiple times and have the tables be distinct?

**Comment by mbibee** [comment]
The above behavior happens because in the template file installed to site-packages/sphinxcontrib/excel_table/templates/table.html the div id maps the content of the table to 

*excel-{{file_name}}-sheet-{{sheet_name}}*

So if you include the directive excel-table:: with the :selection: option then it gets assigned the same div id.  The result in the final html is all content that comes from a particular sheet gets chunked together.

This behavior can be changed if you keep a count of the number of times the directive has been called.  Locally I changed my table template to be

    <div id="excel-{{file_name}}-sheet-{{sheet_name}}-icnt-{{icnt}}" style="margin-bottom: 24px"></div>
    <script>
    var container = document.getElementById('excel-{{file_name}}-sheet-{{sheet_name}}-icnt-{{icnt}}');
    ...

I introduced an "instance count" variable called **icnt** to the template.  In the ExcelTable.run method in excel_table.py I modified the signature to introduce a variable to keep track of the number of times the directive gets called

    def run(self,icnt=[0]):
        # track the number of times the directive is called - send this to jinja template
        icnt[0] += 1  # mutable variable get evaluated ONCE;
        env = self.state.document.settings.env
        ....

I add this variable to the data dict defined further down in the method

        data = {
          'file_name': file_path,
          'sheet_name': sheet_name,
          'overflow': overflow,
          'colwidths': colwidths,
          'row_header': row_header,
          'col_header': col_header,
          'icnt': icnt[0],
        }

When the template is rendered a div is then uniquely identified by the file name, sheet name and a integer count value which represents the nth time the directive was called.  There is probably a better way to do this but it solved my problem.

========== full template table.html ========
<div id="excel-{{file_name}}-sheet-{{sheet_name}}-icnt-{{icnt}}" style="margin-bottom: 24px"></div>
<script>
    var container = document.getElementById('excel-{{file_name}}-sheet-{{sheet_name}}-icnt-{{icnt}}');
    var hot = new Handsontable(container, {
    data: {{content}},
    preventOverflow: {{overflow}},
    readOnly: true,
    colWidths: {{colwidths}},
    manualColumnResize: true,
    manualRowResize: true,
    rowHeaders: {{row_header}},
    colHeaders: {{col_header}},
    mergeCells: {{merged_cells}}
    });
</script>

===========end full template ============

============ modified excel_table.py =======
import os
import re
import json

import docutils.core
from docutils.parsers.rst import Directive
from docutils.parsers.rst import directives

from openpyxl import load_workbook
from jinja2 import Environment, FileSystemLoader

#import wingdbstub

def _get_resource_dir(folder):
    current_path = os.path.dirname(__file__)
    resource_path = os.path.join(current_path, folder)
    return resource_path

def az_to_dec(s):
    if not s:
        return 0

    n = 0
    i = len(s) -1
    j = 1

    while True:
        if i < 0:
            break
        c = s[i].upper()
        n += (ord(c) % 32) * j
        i -= 1
        j *= 26

    return n

class DateTimeEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, date):
            date_string = obj.strftime('%Y-%m-%d')
            return date_string
        if isinstance(obj, datetime):
            datetime_string = obj.strftime("%Y-%m-%d %H:%M:%S")
            return datetime_string
        return json.JSONEncoder.default(self, obj)

def _dumps(data):
    return json.dumps(data, cls=DateTimeEncoder)

class ExcelTable(Directive):

    option_spec = {
        'file': directives.path,
        'sheet': directives.unchanged,
        'rows': directives.unchanged,
        'selection': directives.unchanged,
        'overflow': directives.unchanged,
        'colwidths': directives.unchanged,
        'row_header': directives.unchanged,
        'col_header': directives.unchanged,
    }

    def run(self,icnt=[0]):
        # track the number of times the directive is called - send this to jinja template
        icnt[0] += 1  # mutable variable get evaluated ONCE;
        env = self.state.document.settings.env
        document = self.state.document

        file_path = self.options.get('file')
        selection = self.options.get('selection')
        rows = self.options.get('rows')
        sheet_name = self.options.get('sheet')
        overflow = self.options.get('overflow', 'horizontal')
        colwidths = self.options.get('colwidths', 'undefined')
        row_header = self.options.get('row_header', 'true')
        col_header = self.options.get('col_header', 'true')

        if not file_path:
            msg = "file option is missing"
            return [document.reporter.warning(msg, line=self.lineno)]

        if selection and ':' not in selection:
            msg = "selection must contain a range seperated by :"
            return [document.reporter.warning(msg, line=self.lineno)]

        if rows and ':' not in rows:
            msg = "rows must contain a range seperated by :"
            return [document.reporter.warning(msg, line=self.lineno)]

        relfn, excel_file = env.relfn2path(file_path)
        env.note_dependency(relfn)

        if overflow != 'false':
            overflow = "\'%s\'" % overflow

        data = {
          'file_name': file_path,
          'sheet_name': sheet_name,
          'overflow': overflow,
          'colwidths': colwidths,
          'row_header': row_header,
          'col_header': col_header,
          'icnt': icnt[0],
        }

        wb = load_workbook(filename=excel_file)

        if sheet_name and sheet_name not in wb.sheetnames:
            msg = "sheet %s does not exist" % sheet_name
            return [document.reporter.warning(msg, line=self.lineno)]

        if sheet_name:
            sheet = wb[sheet_name]
        else:
            sheet = wb.worksheets[0]

        if selection:
            sheet_data = sheet[selection]
        elif rows:
            sheet_data = sheet[rows]
        else:
            sheet_data = sheet

        content = []
        for row in sheet_data:
            _row = []
            for cell in row:
                _row.append(cell.value)
            content.append(_row)

        data['content'] = _dumps(content)

        cell_regex = re.compile(r'([A-Z]+){1}([0-9]+){1}')
        merged_cells = []

        #for m in sheet.merged_cell_ranges: #MB
        for m in sheet.merged_cells.ranges: # MB API has changed
            start, end = m.split(":")

            start_match = cell_regex.search(start)
            start_col, start_row = start_match.groups()

            end_match = cell_regex.search(end)
            end_col, end_row = end_match.groups()

            m_row = int(start_row) - 1
            m_col = az_to_dec(start_col) - 1
            m_rowspan = int(end_row) - int(start_row) + 1
            m_colspan = az_to_dec(end_col) - az_to_dec(start_col) + 1

            merged_cells.append({
                "row": m_row,
                "col": m_col,
                "rowspan": m_rowspan,
                "colspan": m_colspan,
            })

        data['merged_cells'] = _dumps(merged_cells)

        loader = FileSystemLoader(_get_resource_dir('templates'))
        _env = Environment(loader=loader,
                           keep_trailing_newline=True,
                           trim_blocks=True,
                           lstrip_blocks=True)

        template = _env.get_template('table.html')
        html = template.render(**data)
        return [docutils.nodes.raw('', html, format='html')]

====== end modified excel_table.py =======

**Comment by hackerain** [comment]
Hello, I have already merged your code to master, and publish it to version 1.0.6, it's a wonderful fix, very thanks for your participation.
