### ISSUE TITLE
Does not work in subdirectories

### ISSUE THREAD

**Issue by Holzhauer** [hackerain/sphinxcontrib-excel-table#10]
When the directive is used in a file stored in a subdirectory, the relative path to the static content as given in the template file is not working. The workaround is to edit the template (adding "../" for files on the level below the first) or to store all files which include the directive on first level.

An improved implementation should be possible as paths to standard sphinx js files are adapted automatically in HTML files.

**Comment by msimoni18** [comment]
I'm running into this same issue. @Holzhauer - what did you change specifically to get it to work?

**Comment by Holzhauer** [comment]
Sorry, I just realised that I mixed the template file `layout.html` with [sphinxcontrib-excel](https://github.com/pyexcel-renderers/sphinxcontrib-excel). For [sphinxcontrib-excel-table](https://github.com/hackerain/sphinxcontrib-excel-table) it actually works. Maybe you don't have the layout (`_template/layout.html`), css (`_static/handsontable.full.min.css`) or library (`_static/handsontable.full.min.js`) files in the right place?
