### ISSUE TITLE
Deprecation warning for function merged_cell_ranges

### ISSUE THREAD

**Issue by ddidier** [hackerain/sphinxcontrib-excel-table#3]
Using version 1.0.4:

`/usr/local/lib/python3.6/site-packages/sphinxcontrib/excel_table/excel_table.py:132: DeprecationWarning: Call to deprecated function merged_cell_ranges (Use ws.merged_cells.ranges).`

**Comment by hackerain** [comment]
Hi, I have already fixed this in version 1.0.6, thanks for your participation
