### ISSUE TITLE
NameError: name 'date' is not defined

### ISSUE THREAD

**Issue by FrancineB** [hackerain/sphinxcontrib-excel-table#4]
I have this error when I want use it
File "/usr/lib/python3.6/site-packages/sphinxcontrib/excel_table/excel_table.py", line 38, in default
    if isinstance(obj, date):
NameError: name 'date' is not defined

**Comment by timboss** [comment]
Found the same error. 

Resolved by manually importing datetime and changing pointers in excel_table.py

New to python, so not quite sure if this is this is correct

[excel_table.zip](https://github.com/hackerain/sphinxcontrib-excel-table/files/2716168/excel_table.zip)

**Comment by hackerain** [comment]
Hi, I have already fixed this in version 1.0.6, thanks for your participation
